### PR TITLE
Sprint 3 Release

### PR DESCRIPTION
**Pull request by willkill07**

### CODE REVIEW

**Review by smschwartz — APPROVED** [review]
sprint 3 release

**Review by JMLovegren — APPROVED** [review]
This is really cool. This should also help us get around some problems we have in passing stuff around

**Review by JMLovegren — CHANGES_REQUESTED** [review]
cleanup your code more before we merge it

**Review by JMLovegren — APPROVED** [review]
Thanks for getting this in!

**Pull request merged**
