### PR TITLE
Cli

### PR DESCRIPTION
**Pull request by IRWeidman**

### CODE REVIEW

**Comment by JMLovegren** [comment]
Need to cut the PRESS ENTER TO CONTINUE at the end of command handler

**Review by Gmzakros — CHANGES_REQUESTED** [review]
loading and new game now works great and I see you removed the press enter thing. but there is one thing every time you enter a command this is printed right under where you enter the command
'clear' is not recognized as an internal or external command,
operable program or batch file.
I think this might be coming from the command Handler line 27-31 fi you could resolve this this would be perfecto merge. Also discard the changes to the pycache files so there no merge conflict

**Review by JMLovegren — APPROVED** [review]
Changes look good, working on resolving merge conflicts now

**Comment by JMLovegren** [comment]
I am not able to handle these merge requests. Delete pycache from yout branch and pus again

**Review by JMLovegren — APPROVED** [review]

**Pull request merged**
