### PR TITLE
Making tests

### PR DESCRIPTION
**Pull request by Gmzakros**
created tests for 2 modules StateStorage and saveState

### CODE REVIEW

**Comment by JMLovegren** [comment]
I see these tests are all in a seperate folder called test. Should these be runnable from that file, or are we still dealing with some technical issues with directories?

**Comment by JMLovegren** [comment]
The tests themselves all look great, but I just wanted to check

**Comment by Gmzakros** [comment]
> The tests themselves all look great, but I just wanted to check



> I see these tests are all in a seperate folder called test. Should these be runnable from that file, or are we still dealing with some technical issues with directories?

There is an __init__.py in that folder but I am thinking of just moving it to main since it would be easier to test like that than dealing with getting that file working. On the other hand I can research how to get that working if that would work better to keep stuff organized

**Review by JMLovegren — APPROVED** [review]
The tests all look great, I can't think of anything that it doesn't cover. If we can crack the directory puzzle, then this will be a quick update.

**Pull request merged**
